name: sawub
services:
  w0rker:
    public: true
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 900m
      memory: 2Gi
    volumes:
      - w0rker:/data
 
volumes:
  w0rker:
    size: 1Gi